<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tableau de bord Propriétaire</title>
    <link rel="stylesheet" href="/css/style.css">

</head>

<body>
    <h1>Bienvenue, Propriétaire</h1>
    <p>Voici votre tableau de bord.</p>
    <!-- Bouton pour créer une annonce -->
    <a href="create_announcement.phtml">
        <button>Créer une Annonce</button>
    </a>
    <!-- Bouton pour voir les annonces -->
    <a href="my_announcements.phtml">
        <button>Mes Annonces</button>
    </a>
</body>

</html>