<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tableau de bord Utilisateur</title>
    <link rel="stylesheet" href="/css/style.css">
</head>

<body>
    <h1>Bienvenue, Utilisateur</h1>
    <p>Voici votre tableau de bord personnel.</p>
    <!-- Bouton pour accéder aux réservations -->
    <a href="reservations.phtml">
        <button>Mes Réservations</button>
    </a>
</body>

</html>